channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - pandas
  - r-base
  - r-forecast
  - r-data.table
  - r-tidyverse
  - r-furrr
  - scikit-learn
  - statsmodels
  - setuptools=58.2.0
  - pip:
    - fastcore
    - hyperopt
    - tqdm 
    - pytorch-lightning>=1.3.0
    - torch==1.9.0
    - jupyterlab
    - parse
